### ISSUE TITLE
Картинка города в фоне

### ISSUE THREAD

**Issue by arsentver** [IrinaDargele/GOODKASSA#1]
Нужно сделать фоновое изображение города более видимым, сейчас теряется на сером фоне - город хоть и стоит фоном, он как бы создаёт общую композицию с кассой. И судя по весу картинки её, возможно, лучше будет сделать не фоновой, а реальной картинкой с позиционированием - она весит около мегабайта, столько обычно весит весь сайт)

**Comment by IrinaDargele** [comment]
исправлено
