### ISSUE TITLE
Маркеры пунктов лучше сделать не через img

### ISSUE THREAD

**Issue by arsentver** [IrinaDargele/GOODKASSA#5]
img - это контентная графика, галочки и кружочки ею не являются, это интерфейсные картинки и их лучше делать фоновыми или через svg
https://yadi.sk/i/RXW1XfmmHbLugA
Хоть семантика для лендинга не является обязательным условием, но в данном случае это можно было хорошо оптимизировать и сделать меньше элементов в DOM

**Comment by IrinaDargele** [comment]
исправлено
