### ISSUE TITLE
Оптимизация изображений

### ISSUE THREAD

**Issue by arsentver** [IrinaDargele/GOODKASSA#8]
Страница очень медленно загружается из-за большого количества графики, её нужно по максимуму оптимизировать, использовать современный формат webp с запасным png, для этого используется тег picture
https://yadi.sk/i/0rbS-gcxLY-Ufw
https://yadi.sk/i/64uPnwGRFVHRZQ
Результат с использованием webp в несколько раз меньше чем в png
Сервис для оптимизации - https://squoosh.app

**Comment by IrinaDargele** [comment]
исправлено
